theme: jekyll-theme-midnight
title: BunnyCDN CLI
description: CLI for the BunnyCDN provider (v0.0.3)
home_url: https://dkfn.github.io/bunnycdn-cli/
docs_url: https://dkfn.github.io/bunnycdn-cli/docs/index
install_url: https://dkfn.github.io/bunnycdn-cli/docs/install

